name: uofncat_app
description: The UofN Catalog App
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: Candara
      fonts:
        - asset: fonts/Candara.ttf
        - asset: fonts/Candara-Italic.ttf
          style: italic
        - asset: fonts/Candara-Bold.ttf
    - family: Optima
      fonts:
        - asset: fonts/Optima.ttf
        - asset: fonts/Optima-Bold.ttf